language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")
before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
script:
  - ./gradlew build
